FROM nginx:1.17.4-alpine

RUN apk add --update nodejs npm

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

WORKDIR /usr/src/app

COPY ./. /usr/src/app/

RUN rm -f .env && mv .env.prod .env

RUN npm install

RUN npm run generate

RUN cp -r dist/. /usr/share/nginx/html/suite_frontend/

EXPOSE 80

