version: '3.3'

services:
  frontend:
    build: ./frontend
    container_name: suite_frontend_dev
    volumes:
      - ./frontend:/usr/src/app/
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/env/.env.dev
    command: 'yarn dev'

  backend:
    build: ./backend
    container_name: suite_backend_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/env/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: suite_db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db

volumes:
  postgres_data: