# Generated by Django 2.2.7 on 2019-11-14 06:11

from django.db import migrations


def create_attribute_types(apps, schema_editor):
    AttributeType = apps.get_model('suite', 'AttributeType')

    attr = AttributeType(name='Text', description='Any text based data')
    attr.save()

    attr = AttributeType(name='Number', description='Any number based data')
    attr.save()

    attr = AttributeType(name='Enum', description='Multiple Options')
    attr.save()

    attr = AttributeType(name='Date', description='Date data')
    attr.save()


def create_risk_types(apps, schema_editor):
    create_risk_type(apps, 'Commercial Property',
                     'Insurance for Commercial properties')
    create_risk_type(apps, 'Automobile', 'Insurance for Automobile Vehicles')
    create_risk_type(apps, 'Personal Life', 'LIfe Insurance for persons')
    create_risk_type(apps, 'HomeOwners', 'Insurance for personal properties')


def create_risk_type(apps, name, description):
    AttributeType = apps.get_model('suite', 'AttributeType')
    Attribute = apps.get_model('suite', 'Attribute')
    RiskType = apps.get_model('suite', 'RiskType')

    text_type = AttributeType.objects.filter(name='Text').first()
    num_type = AttributeType.objects.filter(name='Number').first()
    enum_type = AttributeType.objects.filter(name='Enum').first()
    date_type = AttributeType.objects.filter(name='Date').first()

    r_type = RiskType(name=name, description=description)
    r_type.save()

    attr = Attribute(attribute_type=text_type, label='Name',
                     description='Name of Risk', risk_type=r_type,
                     required=True)
    attr.save()

    attr = Attribute(attribute_type=num_type, label='Age',
                     description='Age of Risk', risk_type=r_type,
                     required=True)
    attr.save()

    attr = Attribute(attribute_type=enum_type, label='Status',
                     description='Status of Risk', risk_type=r_type,
                     options='Valid,Invalid',
                     required=True)
    attr.save()

    attr = Attribute(attribute_type=date_type, label='Effective Date',
                     description='Coverage Start Date', risk_type=r_type,
                     required=True)
    attr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_attribute_types),
        migrations.RunPython(create_risk_types),
    ]
